apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-{{ .Values.environment }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server-{{ .Values.environment }}
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: file-server-{{ .Values.environment }}
        environment: {{ .Values.environment }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: file-server
          image: macnod/file-server:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ros"]
          args:
            - "run"
            - "--"
            - "--eval"
            - "(require :file-server)"
            - "--eval"
            - "(in-package :file-server)"
            - "--eval"
            - "(run)"
          ports:
            - containerPort: 8080
            - containerPort: 4005
          resources:
            requests:
              memory: {{ .Values.fileServer.memory }}
              cpu: {{ .Values.fileServer.requests.cpu }}
            limits:
              memory: {{ .Values.fileServer.memory }}
              cpu: {{ .Values.fileServer.limits.cpu }}
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          env:
            - name: FILE_MANAGER_VERSION
              value: {{ .Values.image.tag | quote }}
            - name: FILE_MANAGER_ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: DB_HOST
              value: postgres-{{ .Values.environment }}-service
            - name: DB_PORT
              value: "{{ .Values.postgres.port }}"
            - name: DB_NAME
              value: "fileserver"
            - name: DB_USER
              value: "fileserver"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-{{ .Values.environment }}-secrets
                  key: postgres-password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-server-{{ .Values.environment }}-secrets
                  key: admin-user-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: file-server-{{ .Values.environment }}-secrets
                  key: jwt-secret
            - name: LOG_SEVERITY
              value: debug
            - name: LOG_SUPPRESS_HEALTH
              value: "true"
            - name: WEB_DIRECTORY
              value: "/app/web"
          volumeMounts:
            - mountPath: /app
              name: file-server-volume
      volumes:
        - name: file-server-volume
          hostPath:
            path: {{ $.Values.postgres.hostPathBase }}/{{ .Values.environment }}
            type: Directory
