apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-{{ .Values.environment }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
  volumeName: pg-{{ .Values.environment }}-pv
  storageClassName: ""
