apiVersion: v1
kind: Service
metadata:
  name: postgres-{{ .Values.environment }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: postgres-{{ .Values.environment }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: 5432
      nodePort: {{ .Values.postgres.nodePort }}
